# Generated by Django 5.1.3 on 2024-11-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_anomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('artifacts_collected', models.ManyToManyField(related_name='stalkers', to='main_app.artifact')),
            ],
        ),
    ]
